#pragma config(Sensor, S1,     light_L,        sensorLightActive)
#pragma config(Sensor, S4,     light_R,        sensorLightActive)
#pragma config(Motor,  motorB,          motor_L,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor_R,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LightValues[32] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
int BounceTimerCounter = 0;

void shiftValue(int a);
int LargestNumber();



task main()
{
	while(true)
	{
		eraseDisplay();
		for(int c = 0; c<8; c++)
		{
			nxtDisplayString(c, "%d", LightValues[c]);
		}
		shiftValue(SensorValue[light_L]);

		if(LightValues[LargestNumber()] > LightValues[0] + 10 && BounceTimerCounter == 0)
		{
			playTone(2000, 10);
			BounceTimerCounter = 25;
		}
		else
		{
			if(BounceTimerCounter > 0) //Voorkomt flow naar negatief naar max
				BounceTimerCounter--;
		}
		wait1Msec(1);
	}
}

void shiftValue(int a)
{
	int TempValues[32] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

	for(int c = 0; c<32; c++)
	{
		TempValues[c] = LightValues[c];
	}
	LightValues[0] = a;

	for(int c = 1; c<32; c++)
	{
		LightValues[c] = TempValues[c-1];
	}
}

int LargestNumber()
{
	int temp = 0;

	for (int c= 0; c<32; c++)
	{
		if(LightValues[temp] < LightValues[c])
		{
			temp = c;
		}
	}
	return temp;
}
