#pragma config(Sensor, S1,     light_L,        sensorLightActive)
#pragma config(Sensor, S4,     light_R,        sensorLightActive)
#pragma config(Motor,  motorB,          motor_L,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor_R,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LightValues[32] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

void shiftValue(int a);

task main()
{
	while(true)
	{
		eraseDisplay();
		for(int c = 0; c<8; c++)
		{
			nxtDisplayString(c, "%d", LigtValues[c]);
		}
		shiftValue(SensorValue[light_L]);
		wait1Msec(500);
	}
	nxtDisplayString(0, "%d", LightValues[1]);
	LightValues[2] = 0;

}

void shiftValue(int a)
{
	int TempValues[32] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

	for(int c = 0; c<32; c++)
	{
		TempValues[c] = LightValues[c];
	}
	LightValues[0] = a;

	for(int c = 1; c<32; c++)
	{
		LightValues[c] = TempValues[c-1];
	}
}
