#pragma config(Sensor, S1,     light_L,        sensorLightActive)
#pragma config(Sensor, S4,     light_R,        sensorLightActive)
#pragma config(Motor,  motorB,          motor_L,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor_R,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (SensorValue(light_L) > 35 && SensorValue(light_R) > 35)
		{
			motor(motor_L) = 80;
			motor(motor_R) = 80;
		}
		if (SensorValue(light_L) > 35 && SensorValue(light_R) < 35)
		{
			motor(motor_L) = 80;
			motor(motor_R) = 50;
		}
			if (SensorValue(light_L) < 35 && SensorValue(light_R) > 35)
		{
			motor(motor_L) = 50;
			motor(motor_R) = 80;
		}
			if (SensorValue(light_L) < 35 && SensorValue(light_R) < 35)
		{
			playTone(600);
			wait1Msec(1);

		}
	}
}
